In [1]:
pip install requests

Requirement already satisfied: requests in c:\users\nhatd\appdata\roaming\python\python311\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nhatd\appdata\roaming\python\python311\site-packages (from requests) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nhatd\appdata\roaming\python\python311\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nhatd\appdata\roaming\python\python311\site-packages (from requests) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nhatd\appdata\roaming\python\python311\site-packages (from requests) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Nhatd\AppData\Roaming\Python\Python311\site-packages\pip-23.1.2.dist-info due to invalid metadata entry 'name'

# Lấy danh sách json phim upcoming

In [2]:
import requests

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

#print(response.text)

# ghi dữ liệu vào file Json và lưu về máy

In [3]:
import json
import requests
import pandas as pd

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)
if response.status_code == 200:
    # Chuyển đổi nội dung JSON thành đối tượng Python
    json_data = json.loads(response.text)

    # Lưu JSON vào một tệp văn bản
    with open("output_upcoming_id.json", "w") as file:
        json.dump(json_data, file, indent=4)
else:
    print("Lỗi khi tải dữ liệu từ API")
#print(response.text)

# đọc file json vừa tạo

In [4]:
with open("output_upcoming_id.json", "r") as file:
    json_dict = json.load(file)

In [5]:
df = pd.DataFrame(json_dict["results"])
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg,"[16, 10751, 10402, 14, 35]",901362,en,Trolls Band Together,"When Branch’s brother, Floyd, is kidnapped for...",1121.642,/qV4fdXXUm5xNlEJ2jw7af3XxuQB.jpg,2023-10-12,Trolls Band Together,False,7.218,229
1,False,/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg,"[18, 36, 10752]",753342,en,Napoleon,An epic that details the checkered rise and fa...,490.701,/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg,2023-11-22,Napoleon,False,6.456,430
2,False,/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg,"[28, 10749, 18]",695721,en,The Hunger Games: The Ballad of Songbirds & Sn...,64 years before he becomes the tyrannical pres...,435.969,/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg,2023-11-15,The Hunger Games: The Ballad of Songbirds & Sn...,False,7.294,498
3,False,/ehumsuIBbgAe1hg343oszCLrAfI.jpg,"[16, 10751, 14, 12]",1022796,en,Wish,"Asha, a sharp-witted idealist, makes a wish so...",345.581,/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg,2023-11-13,Wish,False,6.700,66
4,False,/zgQQF04u3OgNBJqClRNby1FPz9s.jpg,"[16, 10751, 28, 878, 35]",893723,en,PAW Patrol: The Mighty Movie,A magical meteor crash lands in Adventure City...,323.504,/aTvePCU7exLepwg5hWySjwxojQK.jpg,2023-09-21,PAW Patrol: The Mighty Movie,False,6.900,181
5,False,/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg,"[27, 53]",951491,en,Saw X,"Between the events of 'Saw' and 'Saw II', a si...",318.944,/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg,2023-09-26,Saw X,False,7.400,1173
6,False,/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg,"[28, 53, 80]",762430,en,Retribution,When a mysterious caller puts a bomb under his...,292.328,/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg,2023-08-23,Retribution,False,6.991,696
7,False,/zZnsfR6BRqtxyLyAhsi2TMukEBx.jpg,"[16, 28, 80, 9648]",1047041,ja,名探偵コナン 黒鉄の魚影（サブマリン）,Many engineers from around the world gather at...,261.404,/ksQ8uNgoWsVH6a0oPB6zx08pOwU.jpg,2023-04-14,Detective Conan: Black Iron Submarine,False,6.582,49
8,False,/bckxSN9ueOgm0gJpVJmPQrecWul.jpg,"[28, 12, 14]",572802,en,Aquaman and the Lost Kingdom,"Black Manta, still driven by the need to aveng...",195.950,/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg,2023-12-20,Aquaman and the Lost Kingdom,False,0.000,0
9,False,/yUpkacZw40XLWPzFGsGBU1199AL.jpg,"[35, 10751, 14]",787699,en,Wonka,Willy Wonka – chock-full of ideas and determin...,180.822,/qhb1qOilapbapxWQn9jtRCMwXJF.jpg,2023-12-06,Wonka,False,0.000,0
10,False,/igwshQHV36aBkPyWp7En5P4Kn2V.jpg,"[27, 53, 9648]",1071215,en,Thanksgiving,"After a Black Friday riot ends in tragedy, a m...",165.070,/lhmdKoZciQsD6pOxIi0ZkXudISw.jpg,2023-11-16,Thanksgiving,False,6.187,67
11,False,/iEFuHjqrE059SmflBva1JzDJutE.jpg,"[16, 10751, 14, 28, 10749, 10402]",496450,fr,Miraculous - le film,A life of an ordinary Parisian teenager Marine...,164.624,/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg,2023-07-05,"Miraculous: Ladybug & Cat Noir, The Movie",False,7.800,671
12,False,/kszooR7v1TLFM4pzx6IkKq2jDAN.jpg,"[18, 80, 9648]",915935,fr,Anatomie d'une chute,"A woman is suspected of her husband’s murder, ...",130.270,/kQs6keheMwCxJxrzV83VUwFtHkB.jpg,2023-08-23,Anatomy of a Fall,False,7.828,357
13,False,/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg,"[28, 18, 878]",940721,ja,ゴジラ-1.0,"In postwar Japan, a new terror rises. Will the...",140.554,/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg,2023-11-03,Godzilla Minus One,False,8.200,10
14,False,/c7MRmF3LMiBWokedmdQl3roTUv2.jpg,"[53, 18]",798362,en,The Marsh King's Daughter,"Helena, a woman living a seemingly ordinary li...",132.404,/bcuEjrwhp5HgEUnFe5lc4xpEqzt.jpg,2023-09-28,The Marsh King's Daughter,False,6.900,37
15,False,/qElNES0sHVQcbzvGrTx7ccpGzij.jpg,"[878, 28, 18]",842675,zh,流浪地球2,Humans built huge engines on the surface of th...,114.648,/pR858ihc6Ls9xohpdRJVjV787ml.jpg,2023-01-22,The Wandering Earth II,False,7.221,400
16,False,/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg,"[35, 18]",840430,en,The Holdovers,A curmudgeonly instructor at a New England pre...,135.617,/VHSzNBTwxV8vh7wylo7O9CLdac.jpg,2023-10-27,The Holdovers,False,8.000,61
17,False,/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg,"[10751, 16, 14, 35]",1139087,en,Once Upon a Studio,"Created for Disney's 100th anniversary, the sh...",85.189,/hr8ZtwdbtjBquxlTCrczr685K5T.jpg,2023-09-24,Once Upon a Studio,False,8.437,246
18,False,/w1ZeZ8XYTBCovnXi9bwi7D7glM4.jpg,"[28, 80, 53]",891699,en,Silent Night,A tormented father witnesses his young son die...,88.767,/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg,2023-11-30,Silent Night,False,7.600,6
19,False,/dp0rdbGSbZTyWumnbWspXQp87hA.jpg,"[27, 9648]",1024773,en,It Lives Inside,"Desperate to fit in at school, Sam rejects her...",92.661,/73gIfV8gDwkVgUrFDzt4TfZC9Zc.jpg,2023-09-06,It Lives Inside,False,5.773,88

In [6]:
df["id"]

0      901362
1      753342
2      695721
3     1022796
4      893723
5      951491
6      762430
7     1047041
8      572802
9      787699
10    1071215
11     496450
12     915935
13     940721
14     798362
15     842675
16     840430
17    1139087
18     891699
19    1024773
Name: id, dtype: int64

# Lấy danh sách id IMDB từ id trên TMDB của các bộ phim sắp chiếu và ghi vào file JSON

In [7]:
import requests
id_list = df["id"].tolist()
id_list
base_url = "https://api.themoviedb.org/3/movie/"
language = "us-US"
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjN2ZmNDQyZWY5MWQyMGQ1MmJjMDhhOTgzMWFkOGVlZiIsInN1YiI6IjY1MjE2ZjRlYzFmZmJkMDExYjQzNTJlOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.G4CsJ9HQFeIKiIKirMnBbgjnFxo71z-36lqU2hLaUG8"
}
with open("output_IMDB_id.json", "w") as file:
    pass
data_list = []
for movie_id in id_list:
    url = f"{base_url}{movie_id}?language={language}"
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
    # Chuyển đổi nội dung JSON thành đối tượng Python
        json_data = json.loads(response.text)
    data_list.append(json_data)
result_dict = {
    "results": data_list
}
# Mở tệp tin để ghi dữ liệu
with open("output_IMDB_id.json", "w") as file:
    json.dump(result_dict, file, indent=4)

# Đọc file JSON imdb id vừa tạo

In [8]:
with open("output_IMDB_id.json", "r") as file:
    json_dict = json.load(file)
    formatted_json = json.dumps(json_dict, indent=4)
    #print(formatted_json)

In [9]:
df = pd.DataFrame(json_dict["results"])
df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg,"{'id': 489724, 'name': 'The Trolls Collection'...",95000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",https://www.dreamworks.com/movies/trolls-band-...,901362,tt14362112,en,Trolls Band Together,...,2023-10-12,145800000,92,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,There are some new trolls on the block.,Trolls Band Together,False,7.218,229
1,False,/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg,None,165000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",https://www.napoleon.movie,753342,tt13287846,en,Napoleon,...,2023-11-22,78800000,158,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,He came from nothing. He conquered everything.,Napoleon,False,6.458,428
2,False,/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg,None,100000000,"[{'id': 28, 'name': 'Action'}, {'id': 10749, '...",https://hungergames.movie,695721,tt10545296,en,The Hunger Games: The Ballad of Songbirds & Sn...,...,2023-11-15,169082191,157,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Everyone hungers for something.,The Hunger Games: The Ballad of Songbirds & Sn...,False,7.294,498
3,False,/ehumsuIBbgAe1hg343oszCLrAfI.jpg,None,175000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",https://movies.disney.com/wish,1022796,tt11304740,en,Wish,...,2023-11-13,49000000,95,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Be careful what you wish for.,Wish,False,6.700,66
4,False,/zgQQF04u3OgNBJqClRNby1FPz9s.jpg,"{'id': 893731, 'name': 'PAW Patrol (Theatrical...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",https://www.pawpatrol.movie,893723,tt15837338,en,PAW Patrol: The Mighty Movie,...,2023-09-21,192400000,92,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Unleash your powers.,PAW Patrol: The Mighty Movie,False,6.900,181
5,False,/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg,"{'id': 656, 'name': 'Saw Collection', 'poster_...",13000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",https://www.saw.movie,951491,tt21807222,en,Saw X,...,2023-09-26,100900000,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Witness the return of Jigsaw.,Saw X,False,7.400,1173
6,False,/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg,None,20000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",https://www.lionsgate.com/movies/retribution,762430,tt6906292,en,Retribution,...,2023-08-23,16700000,91,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,All roads lead to the truth.,Retribution,False,6.991,696
7,False,/zZnsfR6BRqtxyLyAhsi2TMukEBx.jpg,"{'id': 39199, 'name': 'Detective Conan Collect...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...",,1047041,tt27521477,ja,名探偵コナン 黒鉄の魚影（サブマリン）,...,2023-04-14,0,110,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,,Detective Conan: Black Iron Submarine,False,6.700,48
8,False,/bckxSN9ueOgm0gJpVJmPQrecWul.jpg,"{'id': 573693, 'name': 'Aquaman Collection', '...",215000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.aquamanmovie.com,572802,tt9663764,en,Aquaman and the Lost Kingdom,...,2023-12-20,0,124,"[{'english_name': 'English', 'iso_639_1': 'en'...",Post Production,The tide is turning.,Aquaman and the Lost Kingdom,False,0.000,0
9,False,/yUpkacZw40XLWPzFGsGBU1199AL.jpg,None,125000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",https://www.wonkamovie.com,787699,tt6166392,en,Wonka,...,2023-12-06,0,117,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every good thing in this world started with a ...,Wonka,False,0.000,0
10,False,/igwshQHV36aBkPyWp7En5P4Kn2V.jpg,"{'id': 1211888, 'name': 'Thanksgiving Collecti...",15000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://thanksgiving.movie,1071215,tt1448754,en,Thanksgiving,...,2023-11-16,29100000,106,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,There will be no leftovers.,Thanksgiving,False,6.187,67
11,False,/iEFuHjqrE059SmflBva1JzDJutE.jpg,None,86000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",https://www.netflix.com/title/81383247,496450,tt10364034,fr,Miraculous - le film,...,2023-07-05,38955339,107,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,The fate of the world is in their hands.,"Miraculous: Ladybug & Cat Noir, The Movie",False,7.800,671
12,False,/kszooR7v1TLFM4pzx6IkKq2jDAN.jpg,None,6200000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://anatomyofafall.film,915935,tt17009710,fr,Anatomie d'une chute,...,2023-08-23,17700000,152,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Did she do it?,Anatomy of a Fall,False,7.828,357
13,False,/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg,None,15000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",,940721,tt23289160,ja,ゴジラ-1.0,...,2023-11-03,14000000,125,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,Postwar Japan. From zero to minus.,Godzilla Minus One,False,8.200,10
14,False,/c7MRmF3LMiBWokedmdQl3roTUv2.jpg,None,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",https://www.lionsgate.com/movies/the-marsh-kin...,798362,tt8002382,en,The Marsh King's Daughter,...,2023-09-28,0,108,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Fear the past or face it.,The Marsh King's Daughter,False,6.900,37
15,False,/qElNES0sHVQcbzvGrTx7ccpGzij.jpg,"{'id': 1073029, 'name': 'Wandering Earth Colle...",73801827,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://trinitycineasia.com/in-cinemas/the-wan...,842675,tt13539646,zh,流浪地球2,...,2023-01-22,604380922,173,"[{'english_name': 'Mandarin', 'iso_639_1': 'zh...",Released,,The Wandering Earth II,False,7.221,400
16,False,/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg,None,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://focusfeatures.com/the-holdovers,840430,tt14849194,en,The Holdovers,...,2023-10-27,0,133,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Discomfort and joy.,The Holdovers,False,7.951,61
17,False,/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg,None,0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",,1139087,tt28035641,en,Once Upon a Studio,...,2023-09-24,0,9,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,100 years of Disney magic comes together.,Once Upon a Studio,False,8.437,246
18,False,/w1ZeZ8XYTBCovnXi9bwi7D7glM4.jpg,None,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",,891699,tt15799866,en,Silent Night,...,2023-11-30,0,104,"[{'english_name': 'No Language', 'iso_639_1': ...",Released,Action speaks louder than words.,Silent Night,False,7.600,6
19,False,/dp0rdbGSbZTyWumnbWspXQp87hA.jpg,None,0,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",https://neonrated.com/films/it-lives-inside,1024773,tt15683734,en,It Lives Inside,...,2023-09-06,4800000,99,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,You can't contain evil.,It Lives Inside,False,5.773,88

In [10]:
upcoming_data = df[['id', 'imdb_id', 'budget', 'revenue']]
upcoming_data

         id     imdb_id     budget    revenue
0    901362  tt14362112   95000000  145800000
1    753342  tt13287846  165000000   78800000
2    695721  tt10545296  100000000  169082191
3   1022796  tt11304740  175000000   49000000
4    893723  tt15837338   30000000  192400000
5    951491  tt21807222   13000000  100900000
6    762430   tt6906292   20000000   16700000
7   1047041  tt27521477          0          0
8    572802   tt9663764  215000000          0
9    787699   tt6166392  125000000          0
10  1071215   tt1448754   15000000   29100000
11   496450  tt10364034   86000000   38955339
12   915935  tt17009710    6200000   17700000
13   940721  tt23289160   15000000   14000000
14   798362   tt8002382          0          0
15   842675  tt13539646   73801827  604380922
16   840430  tt14849194          0          0
17  1139087  tt28035641          0          0
18   891699  tt15799866          0          0
19  1024773  tt15683734          0    4800000

## đã có list data của phim upcoming, tiếp theo cần dựa vô cái data frame này để đi truy vấn người tham gia làm từng bộ phim, cần truy vấn SQL trên python, postgres để lấy rating, imdb_id của mấy bộ phim quá khứ liên quan đó