In [3]:
pip install requests

Requirement already satisfied: requests in c:\users\nhatd\anaconda3\lib\site-packages (2.29.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nhatd\anaconda3\lib\site-packages (from requests) (2023.5.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nhatd\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nhatd\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nhatd\anaconda3\lib\site-packages (from requests) (1.26.15)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install minio

Collecting minio
  Downloading minio-7.1.17-py3-none-any.whl (78 kB)
     ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
     ---------------------------------------- 78.3/78.3 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in c:\users\nhatd\anaconda3\lib\site-packages (from minio) (1.26.15)
Requirement already satisfied: certifi in c:\users\nhatd\anaconda3\lib\site-packages (from minio) (2023.5.7)
Installing collected packages: minio
Successfully installed minio-7.1.17
Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests

#url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"
url = "https://api.themoviedb.org/3/movie/550?api_key=781d8b0f33163181d96d61fa21ea16a4"
headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

{"adult":false,"backdrop_path":"/hZkgoQYus5vegHoetLkCJzb17zJ.jpg","belongs_to_collection":null,"budget":63000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.foxmovies.com/movies/fight-club","id":550,"imdb_id":"tt0137523","original_language":"en","original_title":"Fight Club","overview":"A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.","popularity":105.447,"poster_path":"/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg","production_companies":[{"id":711,"logo_path":"/tEiIH5QesdheJmDAqQwvtN60727.png","name":"Fox 2000 Pictures","origin_country":"US"},{"id":508,"logo_path":"/7cxRWzi4LsVm4Utfpr1hfARNurT.png","name":"Regency Enterprises","origin_country":"US"},{"id":4700,"logo_path":"/A32wmjrs9Psf4zw0uaixF0GXfxq.png","name":"The Linson Company","origin_country":"US"},{"id":25,"logo_path":"/qZCc1lty5FzX30aOCVRBLzaVmcp.png","name":"20th Century Fox","origin_country":"US"},{"id":20555,"logo_path":"/hD8yEGUBlHOcfHYbujp71vD8gZp.png","name":"Taurus Film","origin_country":"DE"}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1999-10-15","revenue":100853753,"runtime":139,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Mischief. Mayhem. Soap.","title":"Fight Club","video":false,"vote_average":8.44,"vote_count":27557}

In [6]:
import requests

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

print(response.text)

{"dates":{"maximum":"2023-10-26","minimum":"2023-10-03"},"page":1,"results":[{"adult":false,"backdrop_path":"/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg","genre_ids":[28,18],"id":678512,"original_language":"en","original_title":"Sound of Freedom","overview":"The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.","popularity":1873.942,"poster_path":"/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg","release_date":"2023-07-03","title":"Sound of Freedom","video":false,"vote_average":8,"vote_count":553},{"adult":false,"backdrop_path":"/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg","genre_ids":[27,9648,53],"id":968051,"original_language":"en","original_title":"The Nun II","overview":"In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.","popularity":1867.519,"poster_path":"/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg","release_date":"2023-09-06","title":"The Nun II","video":false,"vote_average":6.6,"vote_count":401},{"adult":false,"backdrop_path":"/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg","genre_ids":[28,9648,53,80],"id":762430,"original_language":"en","original_title":"Retribution","overview":"When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.","popularity":1075.645,"poster_path":"/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg","release_date":"2023-08-23","title":"Retribution","video":false,"vote_average":6.8,"vote_count":280},{"adult":false,"backdrop_path":"/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg","genre_ids":[80,27,53],"id":951491,"original_language":"en","original_title":"Saw X","overview":"Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.","popularity":823.002,"poster_path":"/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg","release_date":"2023-09-26","title":"Saw X","video":false,"vote_average":7.4,"vote_count":78},{"adult":false,"backdrop_path":"/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg","genre_ids":[878,28,53],"id":670292,"original_language":"en","original_title":"The Creator","overview":"Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.","popularity":540.32,"poster_path":"/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg","release_date":"2023-09-27","title":"The Creator","video":false,"vote_average":7.2,"vote_count":181},{"adult":false,"backdrop_path":"/h0nmmdFAdBjQttN8Y0q825MWzZp.jpg","genre_ids":[28,53,80],"id":926393,"original_language":"en","original_title":"The Equalizer 3","overview":"Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.","popularity":499.603,"poster_path":"/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg","release_date":"2023-08-30","title":"The Equalizer 3","video":false,"vote_average":7,"vote_count":287},{"adult":false,"backdrop_path":"/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg","genre_ids":[28,12,53],"id":299054,"original_language":"en","original_title":"Expend4bles","overview":"Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.","popularity":324.751,"poster_path":"/nbrqj9q8WubD3QkYm7n3GhjN7kE.jpg","release_date":"2023-09-15","title":"Expend4bles","video":false,"vote_average":6.7,"vote_count":96},{"adult":false,"backdrop_path":"/f33XdT6dwNXmXQNvQ4FuyhQrUob.jpg","genre_ids":[27],"id":807172,"original_language":"en","original_title":"The Exorcist: Believer","overview":"Since the death of his wife 12 years ago, Victor Fielding has raised their daughter, Angela on his own. But when Angela and her friend Katherine disappear in the woods, only to return three days later with no memory of what happened to them, it unleashes a chain of events that will force Victor to confront the nadir of evil and, in his terror and desperation, seek out the only person alive who has witnessed anything like it before: Chris MacNeil.","popularity":320.029,"poster_path":"/qVKirUdmoex8SdfUk8WDDWwrcCh.jpg","release_date":"2023-10-04","title":"The Exorcist: Believer","video":false,"vote_average":6.6,"vote_count":5},{"adult":false,"backdrop_path":"/nrp2khEM6JWFqqNLeub1J6Qafe0.jpg","genre_ids":[53,80,18,9648],"id":866463,"original_language":"en","original_title":"Reptile","overview":"Following the brutal murder of a young real estate agent, a hardened detective attempts to uncover the truth in a case where nothing is as it seems, and by doing so dismantles the illusions in his own life.","popularity":291.388,"poster_path":"/soIgqZBoTiTgMqUW0JtxsPWAilQ.jpg","release_date":"2023-09-29","title":"Reptile","video":false,"vote_average":7.2,"vote_count":107},{"adult":false,"backdrop_path":"/qEm4FrkGh7kGoEiBOyGYNielYVc.jpg","genre_ids":[53,27],"id":635910,"original_language":"en","original_title":"The Last Voyage of the Demeter","overview":"The crew of the merchant ship Demeter attempts to survive the ocean voyage from Carpathia to London as they are stalked each night by a merciless presence onboard the ship.","popularity":236.822,"poster_path":"/nrtbv6Cew7qC7k9GsYSf5uSmuKh.jpg","release_date":"2023-08-09","title":"The Last Voyage of the Demeter","video":false,"vote_average":7.3,"vote_count":740},{"adult":false,"backdrop_path":"/fwXeTKmJvlv7kbH8QDmbykGfMeK.jpg","genre_ids":[16,10751,35,28,878],"id":893723,"original_language":"en","original_title":"PAW Patrol: The Mighty Movie","overview":"A magical meteor crash-lands in Adventure City, gives the PAW Patrol pups superpowers, and transforms them into The Mighty Pups. When the Patrol's archrival Humdinger breaks out of jail and teams up with mad scientist Victoria Vance to steal the powers for themselves, the Mighty Pups must save Adventure City and stop the supervillains before it's too late.","popularity":214.444,"poster_path":"/oXnSu4raRAd65QVBQXvdHMC6AuW.jpg","release_date":"2023-09-21","title":"PAW Patrol: The Mighty Movie","video":false,"vote_average":7.7,"vote_count":17},{"adult":false,"backdrop_path":"/vT17lPUglrAzjEqMwjPpIDe49ty.jpg","genre_ids":[16,12,10751,14],"id":459003,"original_language":"uk","original_title":"Мавка: Лісова пісня","overview":"Mavka — a Soul of the Forest and its Warden — faces an impossible choice between love and her duty as guardian to the Heart of the Forest, when she falls in love with a human — the talented young musician Lukas.","popularity":206.949,"poster_path":"/eeJjd9JU2Mdj9d7nWRFLWlrcExi.jpg","release_date":"2023-03-02","title":"Mavka: The Forest Song","video":false,"vote_average":7.3,"vote_count":404},{"adult":false,"backdrop_path":"/iEFuHjqrE059SmflBva1JzDJutE.jpg","genre_ids":[16,10751,28,14,10749],"id":496450,"original_language":"fr","original_title":"Miraculous - le film","overview":"A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.","popularity":206.42,"poster_path":"/bBON9XO9Ek0DjRwMBnJNCwC96Cd.jpg","release_date":"2023-07-05","title":"Miraculous: Ladybug & Cat Noir, The Movie","video":false,"vote_average":7.8,"vote_count":597},{"adult":false,"backdrop_path":"/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg","genre_ids":[16,12,14,10751],"id":939338,"original_language":"fr","original_title":"Pattie et la colère de Poséidon","overview":"An adventurous mouse sets off to battle dangerous creatures in Ancient Greece, including Poseidon.","popularity":181.902,"poster_path":"/gVPw9gRPsZZhzY6cIXp6h6nep5M.jpg","release_date":"2023-01-25","title":"Epic Tails","video":false,"vote_average":6.9,"vote_count":39},{"adult":false,"backdrop_path":"/askg3SMvhqEl4OL52YuvdtY40Yb.jpg","genre_ids":[10751,16,14,10402,35,12],"id":354912,"original_language":"en","original_title":"Coco","overview":"Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.","popularity":166.103,"poster_path":"/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg","release_date":"2017-10-27","title":"Coco","video":false,"vote_average":8.2,"vote_count":17767},{"adult":false,"backdrop_path":"/xWT5F1DNxciNLEMXRl49iq8zvN7.jpg","genre_ids":[14,16,10751],"id":9479,"original_language":"en","original_title":"The Nightmare Before Christmas","overview":"Tired of scaring humans every October 31 with the same old bag of tricks, Jack Skellington, the spindly king of Halloween Town, kidnaps Santa Claus and plans to deliver shrunken heads and other ghoulish gifts to children on Christmas morning. But as Christmas approaches, Jack's rag-doll girlfriend, Sally, tries to foil his misguided plans.","popularity":160.205,"poster_path":"/oQffRNjK8e19rF7xVYEN8ew0j7b.jpg","release_date":"1993-10-09","title":"The Nightmare Before Christmas","video":false,"vote_average":7.8,"vote_count":8504},{"adult":false,"backdrop_path":"/2a9DvjXQQezV0sWqJbIN2mDLgZZ.jpg","genre_ids":[28,18,80],"id":1093485,"original_language":"cn","original_title":"掃毒3︰人在天涯","overview":"Hong Kong police agent Cheung (by Aaron Kwok) works undercover in Kang’s (by Sean Lau) drug cartel, while another undercover cop Au (by Louis Koo) successfully earns their trust in an incident, a brotherly-bond is built among the three. After the Police busts the syndicate in Hong Kong, Kang subsequently hides away in the Golden Triangle, by chance he receives a tip-off about the betrayal within his circle of trust…","popularity":147.895,"poster_path":"/kPjZsEni0KF0IXGXh0kaxNESdGE.jpg","release_date":"2023-07-06","title":"The White Storm 3: Heaven or Hell","video":false,"vote_average":6.8,"vote_count":32},{"adult":false,"backdrop_path":"/o9bbojtrrpl0yriiTmzC3Lp3OhA.jpg","genre_ids":[28,10752],"id":840326,"original_language":"fi","original_title":"Sisu","overview":"Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.","popularity":135.529,"poster_path":"/ygO9lowFMXWymATCrhoQXd6gCEh.jpg","release_date":"2023-01-27","title":"Sisu","video":false,"vote_average":7.5,"vote_count":1330},{"adult":false,"backdrop_path":"/8FhKnPpql374qyyHAkZDld93IUw.jpg","genre_ids":[9648,53,878],"id":536437,"original_language":"en","original_title":"Hypnotic","overview":"A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.","popularity":135.459,"poster_path":"/3IhGkkalwXguTlceGSl8XUJZOVI.jpg","release_date":"2023-05-11","title":"Hypnotic","video":false,"vote_average":6.5,"vote_count":619},{"adult":false,"backdrop_path":"/whB2PJfxrDWwwksprliJTjYbcZJ.jpg","genre_ids":[27,53],"id":507089,"original_language":"en","original_title":"Five Nights at Freddy's","overview":"Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.","popularity":127.388,"poster_path":"/h3hhfWdBhdb2JLMZprQ1IvBe90h.jpg","release_date":"2023-10-25","title":"Five Nights at Freddy's","video":false,"vote_average":0,"vote_count":0}],"total_pages":38,"total_results":741}

In [2]:
import requests

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

print(response.text)

{"dates":{"maximum":"2023-12-20","minimum":"2023-11-29"},"page":1,"results":[{"adult":false,"backdrop_path":"/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg","genre_ids":[16,10751,10402,14,35],"id":901362,"original_language":"en","original_title":"Trolls Band Together","overview":"When Branch’s brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.","popularity":2508.728,"poster_path":"/bkpPTZUdq31UGDovmszsg2CchiI.jpg","release_date":"2023-10-12","title":"Trolls Band Together","video":false,"vote_average":7.268,"vote_count":138},{"adult":false,"backdrop_path":"/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg","genre_ids":[18,36,10752],"id":753342,"original_language":"en","original_title":"Napoleon","overview":"An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.","popularity":748.635,"poster_path":"/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg","release_date":"2023-11-22","title":"Napoleon","video":false,"vote_average":6.398,"vote_count":206},{"adult":false,"backdrop_path":"/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg","genre_ids":[28,12,878],"id":695721,"original_language":"en","original_title":"The Hunger Games: The Ballad of Songbirds \u0026 Snakes","overview":"64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.","popularity":595.362,"poster_path":"/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg","release_date":"2023-11-15","title":"The Hunger Games: The Ballad of Songbirds \u0026 Snakes","video":false,"vote_average":7.2,"vote_count":395},{"adult":false,"backdrop_path":"/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg","genre_ids":[27,53],"id":951491,"original_language":"en","original_title":"Saw X","overview":"Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.","popularity":509.974,"poster_path":"/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg","release_date":"2023-09-26","title":"Saw X","video":false,"vote_average":7.412,"vote_count":1148},{"adult":false,"backdrop_path":"/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg","genre_ids":[28,53,80],"id":762430,"original_language":"en","original_title":"Retribution","overview":"When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks- all with his kids trapped in the back seat.","popularity":426.745,"poster_path":"/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg","release_date":"2023-08-23","title":"Retribution","video":false,"vote_average":6.987,"vote_count":685},{"adult":false,"backdrop_path":"/zgQQF04u3OgNBJqClRNby1FPz9s.jpg","genre_ids":[16,10751,28,878,35],"id":893723,"original_language":"en","original_title":"PAW Patrol: The Mighty Movie","overview":"A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.","popularity":433.682,"poster_path":"/aTvePCU7exLepwg5hWySjwxojQK.jpg","release_date":"2023-09-21","title":"PAW Patrol: The Mighty Movie","video":false,"vote_average":6.927,"vote_count":179},{"adult":false,"backdrop_path":"/ehumsuIBbgAe1hg343oszCLrAfI.jpg","genre_ids":[16,10751,14,12],"id":1022796,"original_language":"en","original_title":"Wish","overview":"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.","popularity":402.462,"poster_path":"/8QtDhh8mnGUEyrJsaeb3kYgDRaA.jpg","release_date":"2023-11-13","title":"Wish","video":false,"vote_average":6.838,"vote_count":37},{"adult":false,"backdrop_path":"/azD31DjpV3PJfjF3h72LVw2WCSD.jpg","genre_ids":[27],"id":807172,"original_language":"en","original_title":"The Exorcist: Believer","overview":"When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, who's been forever altered by what happened to her daughter fifty years ago.","popularity":376.108,"poster_path":"/fFXkAlMH2iQrNknv4eq7LGTkcti.jpg","release_date":"2023-10-04","title":"The Exorcist: Believer","video":false,"vote_average":6.173,"vote_count":600},{"adult":false,"backdrop_path":"/bckxSN9ueOgm0gJpVJmPQrecWul.jpg","genre_ids":[28,12,14],"id":572802,"original_language":"en","original_title":"Aquaman and the Lost Kingdom","overview":"Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.","popularity":217.684,"poster_path":"/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg","release_date":"2023-12-20","title":"Aquaman and the Lost Kingdom","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/mPayGWnbFwlqtE65HjqNDfFGb8I.jpg","genre_ids":[80,18,36],"id":466420,"original_language":"en","original_title":"Killers of the Flower Moon","overview":"When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.","popularity":198.908,"poster_path":"/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg","release_date":"2023-10-18","title":"Killers of the Flower Moon","video":false,"vote_average":7.692,"vote_count":1005},{"adult":false,"backdrop_path":"/iEFuHjqrE059SmflBva1JzDJutE.jpg","genre_ids":[16,10751,14,28,10749],"id":496450,"original_language":"fr","original_title":"Miraculous - le film","overview":"A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.","popularity":204.454,"poster_path":"/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg","release_date":"2023-07-05","title":"Miraculous: Ladybug \u0026 Cat Noir, The Movie","video":false,"vote_average":7.8,"vote_count":663},{"adult":false,"backdrop_path":"/igwshQHV36aBkPyWp7En5P4Kn2V.jpg","genre_ids":[27,53,9648],"id":1071215,"original_language":"en","original_title":"Thanksgiving","overview":"After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.","popularity":166.63,"poster_path":"/lhmdKoZciQsD6pOxIi0ZkXudISw.jpg","release_date":"2023-11-16","title":"Thanksgiving","video":false,"vote_average":6.158,"vote_count":57},{"adult":false,"backdrop_path":"/pIbsQ4Cu8rGWkj8QjD6Sqy9NzAS.jpg","genre_ids":[35,12],"id":1002315,"original_language":"en","original_title":"Please Don't Destroy: The Treasure of Foggy Mountain","overview":"When three friends who live together realize that they don't like their life trajectory, they set off to find a gold treasure that is rumored to be buried in the nearby mountain.","popularity":134.475,"poster_path":"/2WSTjQNamyMoy3kFDemd1os8TNz.jpg","release_date":"2023-11-17","title":"Please Don't Destroy: The Treasure of Foggy Mountain","video":false,"vote_average":6.095,"vote_count":21},{"adult":false,"backdrop_path":"/yOm993lsJyPmBodlYjgpPwBjXP9.jpg","genre_ids":[35,10751,14],"id":787699,"original_language":"en","original_title":"Wonka","overview":"Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.","popularity":117.492,"poster_path":"/qhb1qOilapbapxWQn9jtRCMwXJF.jpg","release_date":"2023-12-06","title":"Wonka","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/f9ErVXAyR9EP5WOOp4i5ivBKsKC.jpg","genre_ids":[35],"id":814776,"original_language":"en","original_title":"Bottoms","overview":"Unpopular best friends PJ and Josie start a high school self-defense club to meet girls and lose their virginity. They soon find themselves in over their heads when the most popular students start beating each other up in the name of self-defense.","popularity":142.549,"poster_path":"/jeyTQrNEpyE1LZIgVlswYh3sc34.jpg","release_date":"2023-08-25","title":"Bottoms","video":false,"vote_average":6.922,"vote_count":206},{"adult":false,"backdrop_path":"/1HzL603WOer58xtnrRYdSIL5K04.jpg","genre_ids":[35,12],"id":912908,"original_language":"en","original_title":"Strays","overview":"When Reggie is abandoned on the mean city streets by his lowlife owner, Doug, Reggie is certain that his beloved owner would never leave him on purpose. But once Reggie falls in with Bug, a fast-talking, foul-mouthed stray who loves his freedom and believes that owners are for suckers, Reggie finally realizes he was in a toxic relationship and begins to see Doug for the heartless sleazeball that he is.","popularity":140.092,"poster_path":"/muDaKftykz9Nj1mhRheMdbuNI9Z.jpg","release_date":"2023-08-17","title":"Strays","video":false,"vote_average":7.546,"vote_count":526},{"adult":false,"backdrop_path":"/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg","genre_ids":[10751,16,14,35],"id":1139087,"original_language":"en","original_title":"Once Upon a Studio","overview":"Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.","popularity":116.961,"poster_path":"/hr8ZtwdbtjBquxlTCrczr685K5T.jpg","release_date":"2023-09-24","title":"Once Upon a Studio","video":false,"vote_average":8.417,"vote_count":241},{"adult":false,"backdrop_path":"/5d1sQtAKsbVjdUuzXWoh2vKtyy7.jpg","genre_ids":[28,18,35],"id":897160,"original_language":"ko","original_title":"용감한 시민","overview":"An expelled boxing champion, who now is a high-school teacher, witnesses intolerable violence and throws her first punch to build justice against it, while putting on a mask.","popularity":71.926,"poster_path":"/6Ea5i6APeTfm4hHh6dg5Z733JVS.jpg","release_date":"2023-10-25","title":"Brave Citizen","video":false,"vote_average":5.0,"vote_count":1},{"adult":false,"backdrop_path":"/rron9HAuS9s7zBF8iCX1tsafxUo.jpg","genre_ids":[18,10749],"id":666277,"original_language":"en","original_title":"Past Lives","overview":"Nora and Hae Sung, two childhood friends, are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.","popularity":98.55,"poster_path":"/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg","release_date":"2023-06-02","title":"Past Lives","video":false,"vote_average":7.92,"vote_count":299},{"adult":false,"backdrop_path":"/a0GM57AnJtNi7lMOCamniiyV10W.jpg","genre_ids":[16,12,14,18],"id":508883,"original_language":"ja","original_title":"君たちはどう生きるか","overview":"While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"","popularity":87.675,"poster_path":"/jDQPkgzerGophKRRn7MKm071vCU.jpg","release_date":"2023-07-14","title":"The Boy and the Heron","video":false,"vote_average":7.2,"vote_count":192}],"total_pages":29,"total_results":563}

In [8]:
import requests

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

print(response.text)

{"genres":[{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"},{"id":99,"name":"Documentary"},{"id":18,"name":"Drama"},{"id":10751,"name":"Family"},{"id":14,"name":"Fantasy"},{"id":36,"name":"History"},{"id":27,"name":"Horror"},{"id":10402,"name":"Music"},{"id":9648,"name":"Mystery"},{"id":10749,"name":"Romance"},{"id":878,"name":"Science Fiction"},{"id":10770,"name":"TV Movie"},{"id":53,"name":"Thriller"},{"id":10752,"name":"War"},{"id":37,"name":"Western"}]}

In [10]:
import requests

url = "https://api.themoviedb.org/3/trending/movie/day?language=en-US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/kHlX3oqdD4VGaLpB8O78M25KfdS.jpg","id":945729,"title":"A Haunting in Venice","original_language":"en","original_title":"A Haunting in Venice","overview":"Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.","poster_path":"/1Xgjl22MkAZQUavvOeBqRehrvqO.jpg","media_type":"movie","genre_ids":[9648,53,80],"popularity":833.745,"release_date":"2023-09-13","video":false,"vote_average":6.817,"vote_count":883},{"adult":false,"backdrop_path":"/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg","id":507089,"title":"Five Nights at Freddy's","original_language":"en","original_title":"Five Nights at Freddy's","overview":"Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.","poster_path":"/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg","media_type":"movie","genre_ids":[27,9648],"popularity":4529.373,"release_date":"2023-10-25","video":false,"vote_average":8.289,"vote_count":1488},{"adult":false,"backdrop_path":"/wsMuEaqX5Sks209lnjWEChCdv3C.jpg","id":790459,"title":"Fingernails","original_language":"en","original_title":"Fingernails","overview":"Anna and Ryan have found true love together. It’s been proven by a controversial test. There’s just one problem: Anna still isn’t sure. Then she meets Amir.","poster_path":"/q04g3un61aeBoheQEso7enM28AF.jpg","media_type":"movie","genre_ids":[10749,878,18,35],"popularity":33.867,"release_date":"2023-10-27","video":false,"vote_average":6.4,"vote_count":13},{"adult":false,"backdrop_path":"/1jKBfRyeyJvBkJSKvNQ4nhIzTSx.jpg","id":787781,"title":"Quiz Lady","original_language":"en","original_title":"Quiz Lady","overview":"A brilliant but tightly wound, gameshow-obsessed young woman, Anne, and her estranged, train-wreck of a sister Jenny, must work together to help cover their mother’s gambling debts. When Anne’s beloved dog is kidnapped, they set out on a wild, cross-country trek to get the cash the only way they know how: by turning Anne into a bona-fide gameshow champion.","poster_path":"/tqKiprkTUfXWi8bOjCl0lHtCwod.jpg","media_type":"movie","genre_ids":[35],"popularity":30.978,"release_date":"2023-09-09","video":false,"vote_average":7.18,"vote_count":25},{"adult":false,"backdrop_path":"/8OFnVab1SxQCPZFyrt1gL929LAP.jpg","id":895549,"title":"NYAD","original_language":"en","original_title":"NYAD","overview":"The remarkable true story of athlete Diana Nyad who, at the age of 60 and with the help of her best friend and coach, commits to achieving her life-long dream: a 110-mile open ocean swim from Cuba to Florida.","poster_path":"/eh1IjDZfDRjgv5NzMBkjN1GzKgy.jpg","media_type":"movie","genre_ids":[18,36],"popularity":36.879,"release_date":"2023-10-18","video":false,"vote_average":7.0,"vote_count":13},{"adult":false,"backdrop_path":"/sBY1M68pNdR30EXJnP9s5V104cF.jpg","id":1064024,"title":"Locked In","original_language":"en","original_title":"Locked In","overview":"A kindly nurse tries to unlock the secrets of a coma patient's injury - and discovers the bitter rivalry, infidelity, betrayal and murder behind them.","poster_path":"/blQaj6biyBMLo34cuFKKwbgjIBz.jpg","media_type":"movie","genre_ids":[53],"popularity":140.748,"release_date":"2023-11-01","video":false,"vote_average":6.3,"vote_count":33},{"adult":false,"backdrop_path":"/micMmUVPwGzw6lqzy96xmCgYxNL.jpg","id":1010928,"title":"Wingwomen","original_language":"fr","original_title":"Voleuses","overview":"Tired of life on the run, two expert thieves and best friends recruit feisty Sam to assist them with one last job — unlike any they’ve done before.","poster_path":"/xveVF87WLz1FM0IwW0MiZBBjKKS.jpg","media_type":"movie","genre_ids":[28,35,18],"popularity":146.276,"release_date":"2023-11-01","video":false,"vote_average":6.2,"vote_count":82},{"adult":false,"backdrop_path":"/628Dep6AxEtDxjZoGP78TsOxYbK.jpg","id":575264,"title":"Mission: Impossible - Dead Reckoning Part One","original_language":"en","original_title":"Mission: Impossible - Dead Reckoning Part One","overview":"Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.","poster_path":"/NNxYkU70HPurnNCSiCjYAmacwm.jpg","media_type":"movie","genre_ids":[28,53],"popularity":1085.398,"release_date":"2023-07-08","video":false,"vote_average":7.7,"vote_count":2043},{"adult":false,"backdrop_path":"/28er4p7B5zMSxUDQKPF1hBsgnys.jpg","id":872906,"title":"Jawan","original_language":"hi","original_title":"जवान","overview":"An emotional journey of a prison warden, driven by a personal vendetta while keeping up to a promise made years ago, recruits inmates to commit outrageous crimes that shed light on corruption and injustice, in an attempt to get even with his past,  and that leads him to an unexpected reunion.","poster_path":"/hHKTXxJ3lN8ruHAg5YvpXIQtjc7.jpg","media_type":"movie","genre_ids":[28,12,53],"popularity":141.575,"release_date":"2023-09-07","video":false,"vote_average":7.332,"vote_count":92},{"adult":false,"backdrop_path":"/zgQQF04u3OgNBJqClRNby1FPz9s.jpg","id":893723,"title":"PAW Patrol: The Mighty Movie","original_language":"en","original_title":"PAW Patrol: The Mighty Movie","overview":"A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.","poster_path":"/aTvePCU7exLepwg5hWySjwxojQK.jpg","media_type":"movie","genre_ids":[16,10751,28,878],"popularity":1129.57,"release_date":"2023-09-21","video":false,"vote_average":6.972,"vote_count":109},{"adult":false,"backdrop_path":"/6uVGHiXkHaPggei7WP5PDDtEHkx.jpg","id":1146302,"title":"Sly","original_language":"en","original_title":"Sly","overview":"His love of film began as an escape from a rocky childhood. From underdog to Hollywood legend, Sylvester Stallone tells his story in this documentary.","poster_path":"/flnrKe85SfgcRCW2KgUhz2Bn9yE.jpg","media_type":"movie","genre_ids":[99],"popularity":35.519,"release_date":"2023-09-16","video":false,"vote_average":7.625,"vote_count":16},{"adult":false,"backdrop_path":"/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg","id":609681,"title":"The Marvels","original_language":"en","original_title":"The Marvels","overview":"Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.","poster_path":"/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg","media_type":"movie","genre_ids":[28,12,878],"popularity":217.847,"release_date":"2023-11-08","video":false,"vote_average":8.4,"vote_count":9},{"adult":false,"backdrop_path":"/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg","id":346698,"title":"Barbie","original_language":"en","original_title":"Barbie","overview":"Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.","poster_path":"/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg","media_type":"movie","genre_ids":[35,12,14],"popularity":571.988,"release_date":"2023-07-19","video":false,"vote_average":7.22,"vote_count":5723},{"adult":false,"backdrop_path":"/lNxR7SmtFxFUfA7n9qtzuaIYvoM.jpg","id":926393,"title":"The Equalizer 3","original_language":"en","original_title":"The Equalizer 3","overview":"Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.","poster_path":"/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg","media_type":"movie","genre_ids":[28,53,80],"popularity":1354.023,"release_date":"2023-08-30","video":false,"vote_average":7.385,"vote_count":1383},{"adult":false,"backdrop_path":"/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg","id":678512,"title":"Sound of Freedom","original_language":"en","original_title":"Sound of Freedom","overview":"The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.","poster_path":"/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg","media_type":"movie","genre_ids":[28,18],"popularity":925.953,"release_date":"2023-07-03","video":false,"vote_average":8.124,"vote_count":1146},{"adult":false,"backdrop_path":"/bMRofddQE58ToKM7GtdJy6MuKoY.jpg","id":862968,"title":"Pain Hustlers","original_language":"en","original_title":"Pain Hustlers","overview":"After losing her job, a single mom falls into a lucrative but ultimately dangerous scheme selling prescription drugs.","poster_path":"/m0gM9jE1KmCkXZRqkeNYEQZdVsZ.jpg","media_type":"movie","genre_ids":[18,80],"popularity":256.638,"release_date":"2023-10-20","video":false,"vote_average":6.605,"vote_count":177},{"adult":false,"backdrop_path":"/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg","id":951491,"title":"Saw X","original_language":"en","original_title":"Saw X","overview":"Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.","poster_path":"/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg","media_type":"movie","genre_ids":[27,53],"popularity":1619.014,"release_date":"2023-09-26","video":false,"vote_average":7.373,"vote_count":823},{"adult":false,"backdrop_path":"/1X7vow16X7CnCoexXh4H4F2yDJv.jpg","id":466420,"title":"Killers of the Flower Moon","original_language":"en","original_title":"Killers of the Flower Moon","overview":"When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.","poster_path":"/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg","media_type":"movie","genre_ids":[80,18,53],"popularity":304.093,"release_date":"2023-10-18","video":false,"vote_average":7.773,"vote_count":743},{"adult":false,"backdrop_path":"/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg","id":980489,"title":"Gran Turismo","original_language":"en","original_title":"Gran Turismo","overview":"The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.","poster_path":"/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg","media_type":"movie","genre_ids":[12,28,18],"popularity":1129.59,"release_date":"2023-08-09","video":false,"vote_average":8.023,"vote_count":1303},{"adult":false,"backdrop_path":"/7zmauCUkwjq9wBWBY1IoV5mi8ju.jpg","id":1044648,"title":"Nuovo Olimpo","original_language":"it","original_title":"Nuovo Olimpo","overview":"Late 1970s. Two 25-year-old men meet by chance and fall madly in love. An unexpected event, however, separates them. For thirty years they still pursue the hope of finding each other again, because they still love each other.","poster_path":"/3nx8pSvAARYOLlZ2MNBlH7vW9jv.jpg","media_type":"movie","genre_ids":[10749,18],"popularity":114.22,"release_date":"2023-11-01","video":false,"vote_average":7.21,"vote_count":31}],"total_pages":1000,"total_results":20000}

In [11]:
import requests

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODFkOGIwZjMzMTYzMTgxZDk2ZDYxZmEyMWVhMTZhNCIsInN1YiI6IjY1MWRhNmVkYzUwYWQyMDBhZDgyZDRlYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jfoB836ahuG6GYsOsAOTORYACLJRO6V7mm0_IUxMLv4"
}

response = requests.get(url, headers=headers)

print(response.text)

{"dates":{"maximum":"2023-11-29","minimum":"2023-11-08"},"page":1,"results":[{"adult":false,"backdrop_path":"/7NRGAtu8E4343NSKwhkgmVRDINw.jpg","genre_ids":[27,9648],"id":507089,"original_language":"en","original_title":"Five Nights at Freddy's","overview":"Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.","popularity":4529.373,"poster_path":"/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg","release_date":"2023-10-25","title":"Five Nights at Freddy's","video":false,"vote_average":8.292,"vote_count":1485},{"adult":false,"backdrop_path":"/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg","genre_ids":[28,18],"id":678512,"original_language":"en","original_title":"Sound of Freedom","overview":"The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.","popularity":925.953,"poster_path":"/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg","release_date":"2023-07-03","title":"Sound of Freedom","video":false,"vote_average":8.1,"vote_count":1145},{"adult":false,"backdrop_path":"/mv8M0PqQYicndU7TGgBAHrI4uUo.jpg","genre_ids":[27,53],"id":744857,"original_language":"es","original_title":"Cuando acecha la maldad","overview":"Residents of a small rural town discover that a demon is about to be born among them. They desperately try to escape before the evil is born, but it may be too late.","popularity":566.498,"poster_path":"/iQ7G9LhP7NRRIUM4Vlai3eOxBAc.jpg","release_date":"2023-10-05","title":"When Evil Lurks","video":false,"vote_average":7.587,"vote_count":127},{"adult":false,"backdrop_path":"/45zVtZx6Tzx3RKeDziK25K9geFf.jpg","genre_ids":[16,10751,10402,14,35],"id":901362,"original_language":"en","original_title":"Trolls Band Together","overview":"When Branch’s brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.","popularity":353.878,"poster_path":"/bkpPTZUdq31UGDovmszsg2CchiI.jpg","release_date":"2023-10-12","title":"Trolls Band Together","video":false,"vote_average":6.327,"vote_count":26},{"adult":false,"backdrop_path":"/xHqTnPtpd9Qd7R0fVtoqxZYM67Q.jpg","genre_ids":[80,53,28],"id":958006,"original_language":"en","original_title":"The Kill Room","overview":"A hitman, his boss, an art dealer and a money-laundering scheme that accidentally turns the assassin into an overnight avant-garde sensation, one that forces her to play the art world against the underworld.","popularity":245.185,"poster_path":"/qKpdy7N6zX05eisopvvviiTwPxb.jpg","release_date":"2023-09-14","title":"The Kill Room","video":false,"vote_average":6.2,"vote_count":34},{"adult":false,"backdrop_path":"/mfm4srsPALxaeOMFFFJ0drXTyXy.jpg","genre_ids":[35,12],"id":912908,"original_language":"en","original_title":"Strays","overview":"When Reggie is abandoned on the mean city streets by his lowlife owner, Doug, Reggie is certain that his beloved owner would never leave him on purpose. But once Reggie falls in with Bug, a fast-talking, foul-mouthed stray who loves his freedom and believes that owners are for suckers, Reggie finally realizes he was in a toxic relationship and begins to see Doug for the heartless sleazeball that he is.","popularity":212.883,"poster_path":"/muDaKftykz9Nj1mhRheMdbuNI9Z.jpg","release_date":"2023-08-17","title":"Strays","video":false,"vote_average":7.533,"vote_count":481},{"adult":false,"backdrop_path":"/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg","genre_ids":[28,12,878],"id":609681,"original_language":"en","original_title":"The Marvels","overview":"Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.","popularity":217.847,"poster_path":"/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg","release_date":"2023-11-08","title":"The Marvels","video":false,"vote_average":8.375,"vote_count":9},{"adult":false,"backdrop_path":"/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg","genre_ids":[27,53],"id":663712,"original_language":"en","original_title":"Terrifier 2","overview":"After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.","popularity":173.206,"poster_path":"/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg","release_date":"2022-10-06","title":"Terrifier 2","video":false,"vote_average":6.793,"vote_count":1465},{"adult":false,"backdrop_path":"/cofs7Y72FkRjALbOOOz8q7Uty6h.jpg","genre_ids":[18,53],"id":944952,"original_language":"en","original_title":"The Royal Hotel","overview":"After running out of money while backpacking in a tiny, male-dominated town in the Australian outback, two friends resort to a working holiday at the Royal Hotel. When the locals behavior starts crossing the line, the girls find themselves trapped in an unnerving situation that grows rapidly out of their control.","popularity":127.992,"poster_path":"/oJwb2PV1LGxDp6Q3lynrjADxOIv.jpg","release_date":"2023-10-06","title":"The Royal Hotel","video":false,"vote_average":5.864,"vote_count":33},{"adult":false,"backdrop_path":"/a0GM57AnJtNi7lMOCamniiyV10W.jpg","genre_ids":[16,12,14,18],"id":508883,"original_language":"ja","original_title":"君たちはどう生きるか","overview":"While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"","popularity":119.136,"poster_path":"/y9xS5NQTBnFjDoXhSFQeGxlmkoM.jpg","release_date":"2023-07-14","title":"The Boy and the Heron","video":false,"vote_average":7.5,"vote_count":84},{"adult":false,"backdrop_path":"/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg","genre_ids":[16,12,14,10751],"id":939338,"original_language":"fr","original_title":"Pattie et la colère de Poséidon","overview":"An adventurous mouse sets off to battle dangerous creatures in Ancient Greece, including Poseidon.","popularity":115.644,"poster_path":"/gVPw9gRPsZZhzY6cIXp6h6nep5M.jpg","release_date":"2023-01-25","title":"Epic Tails","video":false,"vote_average":7.0,"vote_count":45},{"adult":false,"backdrop_path":"/hon92J1oqdrTwcGHXG64G2bXqrJ.jpg","genre_ids":[28,12,878],"id":695721,"original_language":"en","original_title":"The Hunger Games: The Ballad of Songbirds \u0026 Snakes","overview":"64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.","popularity":103.504,"poster_path":"/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg","release_date":"2023-11-15","title":"The Hunger Games: The Ballad of Songbirds \u0026 Snakes","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/mEcCz4Nzw57wJIXo6g69q9NUQih.jpg","genre_ids":[16,10751,14,12],"id":1022796,"original_language":"en","original_title":"Wish","overview":"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force—a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe—the ruler of Rosas, King Magnifico—to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.","popularity":105.776,"poster_path":"/8QtDhh8mnGUEyrJsaeb3kYgDRaA.jpg","release_date":"2023-11-22","title":"Wish","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/8g9ZdvHX6jszRY71aVtpRUmHQzJ.jpg","genre_ids":[18,53],"id":958182,"original_language":"es","original_title":"Heroico","overview":"Luis, an 18-year-old boy with Indigenous roots, enters the Heroic Military College in hopes of ensuring a better future. There, he encounters a rigid and institutionally violent system designed to turn him into a perfect soldier.","popularity":93.151,"poster_path":"/w0iYqKZYoVmyoX0Av4FdsDiDXWo.jpg","release_date":"2023-09-21","title":"Heroic","video":false,"vote_average":6.3,"vote_count":10},{"adult":false,"backdrop_path":"/wOYDsD7WIKsz5DtrnjsvCcEyFJa.jpg","genre_ids":[36,18,10752],"id":753342,"original_language":"en","original_title":"Napoleon","overview":"A personal look at the French military leader’s origins and swift, ruthless climb to emperor, viewed through the prism of Napoleon’s addictive, volatile relationship with his wife and one true love, Josephine.","popularity":93.181,"poster_path":"/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg","release_date":"2023-11-22","title":"Napoleon","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/5ut2rC5H1YE0GnNPpl1csnNvqum.jpg","genre_ids":[28,18,80],"id":1093485,"original_language":"cn","original_title":"掃毒3︰人在天涯","overview":"Hong Kong police agent Cheung (by Aaron Kwok) works undercover in Kang’s (by Sean Lau) drug cartel, while another undercover cop Au (by Louis Koo) successfully earns their trust in an incident, a brotherly-bond is built among the three. After the Police busts the syndicate in Hong Kong, Kang subsequently hides away in the Golden Triangle, by chance he receives a tip-off about the betrayal within his circle of trust…","popularity":88.518,"poster_path":"/kPjZsEni0KF0IXGXh0kaxNESdGE.jpg","release_date":"2023-07-06","title":"The White Storm 3: Heaven or Hell","video":false,"vote_average":6.512,"vote_count":41},{"adult":false,"backdrop_path":"/eXX9PqCgbTVYnnlbGuAz7Lk4E86.jpg","genre_ids":[27,12],"id":1145851,"original_language":"es","original_title":"El hombre del saco","overview":"Explores the Spanish origins of the character's story, where he is a tuberculosis patient from Almeria who will do anything to get well, even consuming the blood of the kids he kidnaps in a sack.","popularity":74.533,"poster_path":"/3EdqlGB2ACpnqsrtKhyacaPhzHK.jpg","release_date":"2023-08-11","title":"El hombre del saco","video":false,"vote_average":5.7,"vote_count":33},{"adult":false,"backdrop_path":"/drfl2eWipiibW3u3Ybx9HQ8VgIn.jpg","genre_ids":[27,9648,53],"id":841742,"original_language":"fr","original_title":"Megalomaniac","overview":"Felix and Martha, the two offspring of legendary serial murderer The Skinner of Mons, grapple with the grotesque legacy bequeathed to them. While Martha works a menial janitorial job, Felix continues his father's reign of terror. But following a brutal attack at work, Martha quickly descends into madness, finding she must come to terms with the infamous blood that flows through her veins.","popularity":69.69,"poster_path":"/bgullymFFblfNaEqRX2j74oTIQ.jpg","release_date":"2023-09-08","title":"Megalomaniac","video":false,"vote_average":6.192,"vote_count":13},{"adult":false,"backdrop_path":"/rron9HAuS9s7zBF8iCX1tsafxUo.jpg","genre_ids":[18,10749],"id":666277,"original_language":"en","original_title":"Past Lives","overview":"Nora and Hae Sung, two childhood friends, are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.","popularity":91.993,"poster_path":"/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg","release_date":"2023-06-02","title":"Past Lives","video":false,"vote_average":7.879,"vote_count":257},{"adult":false,"backdrop_path":"/3xYPGRUsXCZj7rKOzvOY84JCafK.jpg","genre_ids":[18,10749],"id":1020006,"original_language":"en","original_title":"Priscilla","overview":"When teenage Priscilla Beaulieu meets Elvis Presley at a party, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments: a thrilling crush, an ally in loneliness, a vulnerable best friend.","popularity":63.949,"poster_path":"/3eTAdKJzC8biM52Eii1ghk69bMP.jpg","release_date":"2023-10-26","title":"Priscilla","video":false,"vote_average":6.95,"vote_count":10}],"total_pages":29,"total_results":572}

In [3]:
import pandas as pd
#Đọc tệp TSV bằng Polars
df = pd.read_csv("name_basics.tsv", sep='\t')
#Hiển thị dữ liệu
df

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0050419,tt0031983,tt0072308,tt0053137"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0037382,tt0038355,tt0075213"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0057345,tt0049189,tt0054452,tt0056404"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0078723,tt0077975,tt0080455,tt0072562"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0069467,tt0050986,tt0050976,tt0083922"
...,...,...,...,...,...,...
12923126,nm9993714,Romeo del Rosario,\N,\N,"animation_department,art_department","tt2455546,tt14069590,tt11657662"
12923127,nm9993716,Essias Loberg,\N,\N,NaN,\N
12923128,nm9993717,Harikrishnan Rajan,\N,\N,cinematographer,tt8736744
12923129,nm9993718,Aayush Nair,\N,\N,cinematographer,tt8736744
12923130,nm9993719,Andre Hill,\N,\N,NaN,\N

In [4]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12923131 entries, 0 to 12923130
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   nconst             object
 1   primaryName        object
 2   birthYear          object
 3   deathYear          object
 4   primaryProfession  object
 5   knownForTitles     object
dtypes: object(6)
memory usage: 591.6+ MB
None
nconst                     0
primaryName                6
birthYear                  0
deathYear                  0
primaryProfession    2560188
knownForTitles             0
dtype: int64

In [14]:
import pandas as pd
#Đọc tệp TSV bằng Pandas
df2 = pd.read_csv("title_basics.tsv", sep='\t')
#Hiển thị dữ liệu
df2

C:\Users\Nhatd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3505: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
10211020,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,"Action,Drama,Family"
10211021,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
10211022,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
10211023,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
10211024,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [15]:
print(df2[df2['tconst'] == 'tt4589218'])

            tconst titleType             primaryTitle  \
7804323  tt4589218     movie  Five Nights at Freddy's

                   originalTitle isAdult startYear endYear runtimeMinutes  \
7804323  Five Nights at Freddy's       0      2023      \N            110

         genres
7804323  Horror

# Lỗi ở 1 dòng data nên buộc phải xử lý trước khi import vào database

In [58]:
print(df2[df2['tconst'] == 'tt0701219'])

           tconst  titleType    primaryTitle   originalTitle isAdult  \
678244  tt0701219  tvEpisode  Summer of 4'2"  Summer of 4'2"       0

       startYear endYear runtimeMinutes            genres
678244      1996      \N             30  Animation,Comedy

In [16]:
import pandas as pd
#Đọc tệp TSV bằng Polars
df3 = pd.read_csv("title_crew.tsv", sep='\t')
#Hiển thị dữ liệu
df3

,tconst,directors,writers
0,tt0000001,nm0005690,\N
1,tt0000002,nm0721526,\N
2,tt0000003,nm0721526,\N
3,tt0000004,nm0721526,\N
4,tt0000005,nm0005690,\N
...,...,...,...
10232310,tt9916848,nm1485677,"nm9187127,nm1485677,nm9826385,nm9299459,nm1628284"
10232311,tt9916850,nm1485677,"nm9187127,nm1485677,nm9826385,nm1628284"
10232312,tt9916852,nm1485677,"nm9187127,nm1485677,nm9826385,nm9299459,nm1628284"
10232313,tt9916856,nm10538645,nm6951431
10232314,tt9916880,"nm0584014,nm0996406","nm1482639,nm2586970"

In [20]:
import pandas as pd
#Đọc tệp TSV bằng Polars
df4 = pd.read_csv("title_episode.tsv", sep='\t')
#Hiển thị dữ liệu
df4

            tconst parentTconst seasonNumber episodeNumber
0        tt0041951    tt0041038            1             9
1        tt0042816    tt0989125            1            17
2        tt0042889    tt0989125           \N            \N
3        tt0043426    tt0040051            3            42
4        tt0043631    tt0989125            2            16
...            ...          ...          ...           ...
7800113  tt9916846    tt1289683            3            18
7800114  tt9916848    tt1289683            3            17
7800115  tt9916850    tt1289683            3            19
7800116  tt9916852    tt1289683            3            20
7800117  tt9916880    tt0985991            4             2

[7800118 rows x 4 columns]

In [21]:
import pandas as pd
#Đọc tệp TSV bằng Polars
df5 = pd.read_csv("title_principal.tsv", sep='\t')
#Hiển thị dữ liệu
df5

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0374658,cinematographer,director of photography,\N
3,tt0000002,1,nm0721526,director,\N,\N
4,tt0000002,2,nm1335271,composer,\N,\N
...,...,...,...,...,...,...
58519634,tt9916880,5,nm0584014,director,\N,\N
58519635,tt9916880,6,nm0996406,director,principal director,\N
58519636,tt9916880,7,nm1482639,writer,\N,\N
58519637,tt9916880,8,nm2586970,writer,books,\N
58519638,tt9916880,9,nm1594058,producer,producer,\N

In [22]:
print(df5[df5['tconst'] == 'tt4589218'])

             tconst  ordering     nconst  category              job  \
44667494  tt4589218        10  nm0089658  producer         producer
44667495  tt4589218         1  nm0000498     actor               \N
44667496  tt4589218         2  nm1242688     actor               \N
44667497  tt4589218         3  nm5634768   actress               \N
44667498  tt4589218         4  nm0000524   actress               \N
44667499  tt4589218         5  nm0849747  director               \N
44667500  tt4589218         6  nm6926569    writer    screenplay by
44667501  tt4589218         7  nm2417104    writer    screenplay by
44667502  tt4589218         8  nm3273770    writer  screen story by
44667503  tt4589218         9  nm3225709    writer  screen story by

                characters
44667494                \N
44667495  ["Steve Raglan"]
44667496          ["Mike"]
44667497       ["Vanessa"]
44667498     ["Aunt Jane"]
44667499                \N
44667500                \N
44667501                \N
44667502                \N
44667503                \N

In [21]:
df5["job"] = df5["job"].str.replace('"', '').astype(str)
df5["characters"] = df5["characters"].str.replace('"', '').astype(str)

In [22]:
file_path = "output_title_principal.tsv"
df5.to_csv(file_path, sep='\t', index=False)

In [18]:
# Tạo DataFrame từ file txt
import pandas as pd
df6 = pd.read_csv('title_rating.tsv', sep='\t')
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1355266 entries, 0 to 1355265
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tconst         1355266 non-null  object
 1   averageRating  1355266 non-null  float64
 2   numVotes       1355266 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 31.0+ MB

In [19]:
print(df6[df6['tconst'] == 'tt4589218'])

Empty DataFrame
Columns: [tconst, averageRating, numVotes]
Index: []

In [1]:
import pandas as pd
#Đọc tệp TSV bằng Polars
df2 = pd.read_csv("title_basicss.tsv", sep='\t')
#Hiển thị dữ liệu
df2

C:\Users\Nhatd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3505: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
10211020,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,"Action,Drama,Family"
10211021,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
10211022,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
10211023,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
10211024,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [10]:
df2.dtypes

tconst            object
titleType         object
primaryTitle      object
originalTitle     object
isAdult           object
startYear         object
endYear           object
runtimeMinutes    object
genres            object
dtype: object

In [4]:
print(df2[df2['tconst'] == 'tt0701219'])

           tconst  titleType    primaryTitle   originalTitle isAdult  \
678244  tt0701219  tvEpisode  Summer of 4'2"  Summer of 4'2"       0

       startYear endYear runtimeMinutes            genres
678244      1996      \N             30  Animation,Comedy

In [15]:
#df2[df2['tconst'] == 'tt0701219']
df2["primaryTitle"] = df2["primaryTitle"].str.replace('"', '').astype(str)
df2["originalTitle"] = df2["originalTitle"].str.replace('"', '').astype(str)

In [16]:
print(df2[df2['tconst'] == 'tt0701219'])

           tconst  titleType   primaryTitle  originalTitle isAdult startYear  \
678244  tt0701219  tvEpisode  Summer of 4'2  Summer of 4'2       0      1996

       endYear runtimeMinutes            genres
678244      \N             30  Animation,Comedy

In [17]:
df2

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
10211020,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,"Action,Drama,Family"
10211021,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
10211022,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
10211023,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
10211024,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [18]:
file_path = "output123.tsv"
df2.to_csv(file_path, sep='\t', index=False)

In [25]:
import minio
from minio import Minio
#from minio.error import ResponseError

In [28]:
pip install minio

Requirement already satisfied: minio in c:\users\nhatd\anaconda3\lib\site-packages (7.1.17)
Requirement already satisfied: urllib3 in c:\users\nhatd\anaconda3\lib\site-packages (from minio) (1.26.15)
Requirement already satisfied: certifi in c:\users\nhatd\anaconda3\lib\site-packages (from minio) (2023.5.7)
Note: you may need to restart the kernel to use updated packages.

In [32]:
from minio.error import ResponseError

ImportError: cannot import name 'ResponseError' from 'minio.error' (C:\Users\Nhatd\anaconda3\lib\site-packages\minio\error.py)

In [42]:

#Thông tin kết nối đến MinIO server
minio_client = Minio(
    "443",  # Điền vào địa chỉ MinIO server của bạn
    access_key="jUR9KgWerlAL8T1XkUFp",
    secret_key="n5YRiDb6PYXwiFO1RTg2bxkzWW3GQtPYF3lp7vhY",
    secure=True  # Sử dụng True nếu bạn sử dụng kết nối bảo mật (HTTPS)
)

#Tên bucket chứa tệp TSV
bucket_name = "seminar"

#Tên tệp TSV bạn muốn đọc
object_name = "title_basics.tsv"

    # Đọc nội dung tệp TSV từ MinIO
data = minio_client.get_object(bucket_name, object_name)

#Đọc nội dung và hiển thị nó
for line in data.stream(32 * 1024):  # Đọc 32 KB mỗi lần
    print(line.decode('utf-8'))  # Giả sử tệp TSV sử dụng mã hóa UTF-8

# except ResponseError as err:
#     print("Lỗi MinIO: {0}".format(err))

MaxRetryError: HTTPSConnectionPool(host='443', port=443): Max retries exceeded with url: /seminar?location= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021BE3C0A400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))